package it.polimi.ingsw.controller.states;

public enum CONTROLLER_STATES {

    WAITING_PLAYERS_STATE,
    FIRST_ACTION_STATE,
    TAKE_MARBLE_STATE,
    BUY_CARD_STATE,
    ACTIVATE_PRODUCTION_STATE,
    END_TURN_STATE,
    WHITE_CONVERSION_CARD_STATE
}
